name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: 'build'
    condition:  succeeded()
    displayName: 'build mvc'
    jobs:
      - job:
        condition:  succeeded()
        displayName: 'build-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - scripts: |
              echo 'build passed...'

  - stage: 'test'
    condition:  succeeded()
    displayName: 'test mvc'
    jobs:
      - job:
        condition:  succeeded()
        displayName: 'test-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - scripts: |
              echo 'test passed...'

  - stage: 'pack'
    condition:  succeeded()
    displayName: 'pack mvc'
    jobs:
      - job:
        condition:  succeeded()
        displayName: 'pack-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - scripts: |
              echo 'pack passed...'
  
  - stage: 'deploy'
    condition:  succeeded()
    displayName: 'deploy mvc'
    jobs:
      - job:
        condition:  succeeded()
        displayName: 'deploy-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - scripts: |
              echo 'deploy passed...'


triggers:
  - branches:
      include:
        - master 

variables: