name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: 'build'
    condition: succeeded()
    displayName: 'build-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'build-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet build

  - stage: 'test'
    condition: succeeded()
    displayName: 'test-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'test-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet test
  
  - stage: 'pack'
    condition: succeeded()
    displayName: 'pack-mvc'
    jobs:
      - job:
        condition: succeeded()
        dependsOn:
          - test
        displayName: 'pack-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet publish
  
  - stage: 'deploy'
    condition: succeeded()
    dependsOn:
    displayName: 'deploy-mvc'
    jobs:
      - job:
        condition: succeeded()
        dependsOn:
          - test
        displayName: 'deploy-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'deploy succeeded'

trigger:
  branches:
    include:
      - master

variables:
  testVar: 'tuesday'