# devopsworld - pipeline # build defintion

name: $(date:yyyyMMdd)$(rev:.rr) #20190910.00

stages:
  - stage: 'build'
    displayName: 'build-mvc'   # literal value
    jobs:
      - job:
        displayName:
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - step:
            displayName:
            - script: |
               echo 'Hello Pipeline'